### ISSUE TITLE
Update CONTRIBUTING.markdown for Java 6

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-dist#4]
Now that https://github.com/thymeleaf/thymeleaf/issues/414 is done, we need to update this line in our contribution guide:

>  - All your code should compile and run in **Java 5.0.**

**Comment by ultraq** [comment]
Done for this project, but now we need to copy it to pretty much every other Thymeleaf project! O_o

Do you have every project checked out on your machine so you can just drop it into each folder and then mass commit it somehow @danielfernandez ?

**Comment by danielfernandez** [comment]
Yup, I'll do that

**Comment by danielfernandez** [comment]
Done!
